### ISSUE TITLE
App crash in Sign in process on NoClassDefFoundError

### ISSUE THREAD

**Issue by arcao** [arcao/Geocaching4Locus#97]
The app crash while preparing access token request to OAuth service. Unfortunately it crash inside ScribeJava library. It is caused by missing class `Objects`, that was added in Android SDK 19.

Stacktrace:
```
    java.lang.NoClassDefFoundError: java.util.Objects
        at com.github.scribejava.core.model.OAuth1RequestToken.hashCode(OAuth1RequestToken.java:60)
        at java.lang.Object.toString(Object.java:332)
        at java.lang.StringBuilder.append(StringBuilder.java:202)
        at com.github.scribejava.core.oauth.OAuth10aService.prepareAccessTokenRequest(OAuth10aService.java:144)
        at com.github.scribejava.core.oauth.OAuth10aService.getAccessTokenAsync(OAuth10aService.java:131)
        at com.arcao.geocaching4locus.authentication.task.OAuthLoginTask.doInBackground(OAuthLoginTask.java:89)
        at com.arcao.geocaching4locus.authentication.task.OAuthLoginTask.doInBackground(OAuthLoginTask.java:35)
        at com.arcao.geocaching4locus.base.task.UserTask$2.call(UserTask.java:224)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
```

More here: scribejava/scribejava#851

**Comment by arcao** [comment]
Temporarily fixed with workaround.
